[build]
   ignore = "/bin/false"

[[redirects]]
  from = "/proxy/*"
  to = "https://hacker-punk.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
